// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLwCyRuCy55nIvnv_xtzeb6xrII4sXBgs',
    appId: '1:50484837227:web:5711b0da6a10c165222a2e',
    messagingSenderId: '50484837227',
    projectId: 'khirmannotes',
    authDomain: 'khirmannotes.firebaseapp.com',
    storageBucket: 'khirmannotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDagI5yS0TFQ9BtQmuK4PN-9SPMllpPTYA',
    appId: '1:50484837227:android:e147980d037d01bc222a2e',
    messagingSenderId: '50484837227',
    projectId: 'khirmannotes',
    storageBucket: 'khirmannotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJFDUcn53AxlF3NQoufLk08wNYHjbYUXI',
    appId: '1:50484837227:ios:e15f63377a761ece222a2e',
    messagingSenderId: '50484837227',
    projectId: 'khirmannotes',
    storageBucket: 'khirmannotes.appspot.com',
    iosBundleId: 'com.khirmanassociation.noteTakingAppKhirman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJFDUcn53AxlF3NQoufLk08wNYHjbYUXI',
    appId: '1:50484837227:ios:48e28412e27630e2222a2e',
    messagingSenderId: '50484837227',
    projectId: 'khirmannotes',
    storageBucket: 'khirmannotes.appspot.com',
    iosBundleId: 'com.khirmanassociation.noteTakingAppKhirman.RunnerTests',
  );
}
